name: Daily Job Alerts

on:
  schedule:
    # Runs every day at 10:30 AM UTC (4:00 PM IST)
    - cron: "30 10 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run job alert script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python job_alert.py
